
services:
  postgres:
    image: postgres:16-alpine
    container_name: kasir_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kasir_user
      POSTGRES_PASSWORD: kasir_password_secret
      POSTGRES_DB: kasir_db
    ports:
      - "5433:5432"
    volumes:
      - kasir_pgdata:/var/lib/postgresql/data

volumes:
  kasir_pgdata:
